### ISSUE TITLE
move .gcalclirc format to something standard (probably toml)

### ISSUE THREAD

**Issue by jcrowgey** [insanum/gcalcli#416]
gcalclirc has a bit of an awkward format.

pip, tox, other programs in the python ecosystem use toml for configuration files.

related #322 #381

**Comment by dbarnett** [comment]
+1, I had toml in mind as a good format as well.

**Comment by dbarnett** [comment]
I just merged #744 to implement the first bit of toml config. You can now create a config.toml file at some path like ~/.config/gcalcli/config.toml (see `gcalcli --help` for exact path used on your system) and configure default-calendars via that file:
```toml
#:schema https://raw.githubusercontent.com/insanum/gcalcli/HEAD/data/config-schema.json
[calendars]
default-calendars = ["Personal", "Work"]
```

From here it just needs to be filled in with more supported options and have the code cleaned up a bit.
