### ISSUE TITLE
Proper support for alternate auth accounts

### ISSUE THREAD

**Issue by dbarnett** [insanum/gcalcli#807]
There should be a convenient way for users to switch between different authenticated accounts in gcalcli.

Currently this can be done by twiddling oauth files (see #805), but the mechanism is clunky and not very discoverable. The ideal would probably be to have a set of named auth accounts and to be able to configure `--account=someaccount@domain` in cli args and config files.

**Comment by dbarnett** [comment]
Or maybe instead of separate configs per account, the config.toml structure should change to support e.g.
```toml
[accounts."account1@domain".calendars]
ignore-calendars = ["cal1", "cal2"]
```
?
